# Generated by Django 3.2.3 on 2021-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=10, max_length=300),
            preserve_default=False,
        ),
    ]
