# Generated by Django 3.2.3 on 2021-06-26 10:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=60)),
                ('githiblink', models.SlugField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='images')),
                ('text', ckeditor.fields.RichTextField()),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('message', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comment', to='portfolio.portfolio')),
            ],
        ),
    ]
