# Generated by Django 3.2.3 on 2021-05-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='per',
            field=models.IntegerField(max_length=100),
        ),
    ]
