# Generated by Django 3.2.3 on 2021-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_skills_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='per',
            field=models.IntegerField(),
        ),
    ]
