# Generated by Django 3.2.3 on 2021-05-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='CV',
            new_name='cv',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='Img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='main_info',
            old_name='Information',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='main_info',
            old_name='Name',
            new_name='name',
        ),
    ]
